spring:
  datasource:
    url: jdbc:mysql://rm-uf6e4xr978w748b9w7o.mysql.rds.aliyuncs.com:3306/xiaoka_robot?useSSL=false&serverTimezone=GMT%2b8&characterEncoding=UTF8&allowPublicKeyRetrieval=true
    username: "xys"
    password: "232020ctt@"
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 587
    #username: 2879322503@qq.com
    #password: gkemyvdhkfoudgij
    username: 2199386146@qq.com
    password: vlwtxgyxpkdgdjaa
    test-connection: false
    properties:
      mail:
        smtp:
          auth: false
        debug: false
        mime:
          splitlongparameters: false
    default-encoding: UTF-8



mybatis-plus:
  configuration:
    # 开启下划线转驼峰
    map-underscore-to-camel-case: true
    # 指定默认枚举类型的类型转换器
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    # 开启/关闭 banner 打印
    banner: false
    db-config:
      # 逻辑删除（软删除）
      logic-delete-value: NOW()
      logic-not-delete-value: 'NULL'
      # 查询，如果比较的字段为null或者""，则不会当作条件取查询
      select-strategy: not_empty
  # mapper路径位置
  mapper-locations: classpath:mapper/*.xml
  # MyBatis-plus在进行更新操作时不会更新传入实体中为null或默认值属性字段，只更新不为null的值、非默认值的属性字段。

